import type { PromptDifficulty } from "../shared/game";

export interface PromptCard {
  readonly prompt: string;
  readonly category: string;
  readonly difficulty: PromptDifficulty;
  readonly aliases: readonly string[];
  /** Visually plausible but incorrect guesses that must not score. */
  readonly rejectedAnswers: readonly string[];
  readonly practiceEligible: boolean;
}

type PromptSeed = readonly [
  prompt: string,
  category: string,
  aliases: readonly string[],
  rejectedAnswers: readonly string[],
];

// Canonical prompts are deliberately concrete, visually distinct, single-word nouns.
// Alternate regional names, spellings, and common plurals live only in aliases.
const SINGLE_WORD_PROMPT_SEEDS = [
  ["alligator", "animals", ["gator"], ["snake", "shark"]],
  ["ant", "animals", ["ants"], ["spider", "bee"]],
  ["bat", "animals", ["bats"], ["bird", "butterfly"]],
  ["bear", "animals", ["bears"], ["lion", "gorilla"]],
  ["bee", "animals", ["honeybee"], ["fly", "butterfly"]],
  ["beetle", "animals", ["beetles"], ["bee", "spider"]],
  ["butterfly", "animals", ["butterflies"], ["bird", "dragonfly"]],
  ["camel", "animals", ["camels"], ["horse", "giraffe"]],
  ["cat", "animals", ["kitty"], ["dog", "rabbit"]],
  ["chicken", "animals", ["hen"], ["duck", "turkey"]],
  ["crab", "animals", ["crabs"], ["spider", "lobster"]],
  ["deer", "animals", ["stag"], ["horse", "goat"]],
  ["dolphin", "animals", ["dolphins"], ["shark", "whale"]],
  ["donkey", "animals", ["burro"], ["horse", "goat"]],
  ["duck", "animals", ["duckling"], ["swan", "chicken"]],
  ["eagle", "animals", ["eagles"], ["owl", "bat"]],
  ["elephant", "animals", ["elephants"], ["hippo", "rhinoceros"]],
  ["flamingo", "animals", ["flamingos"], ["swan", "ostrich"]],
  ["fox", "animals", ["foxes"], ["cat", "wolf"]],
  ["frog", "animals", ["frogs"], ["turtle", "lizard"]],
  ["giraffe", "animals", ["giraffes"], ["camel", "horse"]],
  ["goat", "animals", ["goats"], ["sheep", "deer"]],
  ["gorilla", "animals", ["gorillas"], ["bear", "monkey"]],
  ["hamster", "animals", ["hamsters"], ["mouse", "rabbit"]],
  ["hedgehog", "animals", ["hedgehogs"], ["porcupine", "mouse"]],
  ["hippo", "animals", ["hippopotamus"], ["rhinoceros", "elephant"]],
  ["horse", "animals", ["stallion"], ["donkey", "cow"]],
  ["jellyfish", "animals", ["jelly fish"], ["octopus", "squid"]],
  ["kangaroo", "animals", ["kangaroos"], ["rabbit", "deer"]],
  ["koala", "animals", ["koalas"], ["panda", "bear"]],
  ["ladybug", "animals", ["ladybird"], ["beetle", "butterfly"]],
  ["lion", "animals", ["lions"], ["tiger", "bear"]],
  ["lobster", "animals", ["lobsters"], ["crab", "shrimp"]],
  ["monkey", "animals", ["monkeys"], ["gorilla", "bear"]],
  ["octopus", "animals", ["octopuses"], ["jellyfish", "spider"]],
  ["owl", "animals", ["owls"], ["eagle", "penguin"]],
  ["panda", "animals", ["pandas"], ["bear", "koala"]],
  ["penguin", "animals", ["penguins"], ["duck", "owl"]],
  ["pig", "animals", ["piglet"], ["hippo", "cow"]],
  ["rabbit", "animals", ["bunny"], ["cat", "hamster"]],
  ["raccoon", "animals", ["racoons"], ["cat", "fox"]],
  ["rhinoceros", "animals", ["rhino"], ["elephant", "hippo"]],
  ["scorpion", "animals", ["scorpions"], ["lobster", "spider"]],
  ["seal", "animals", ["seals"], ["dolphin", "penguin"]],
  ["shark", "animals", ["sharks"], ["whale", "dolphin"]],
  ["snail", "animals", ["snails"], ["turtle", "worm"]],
  ["spider", "animals", ["spiders"], ["ant", "scorpion"]],
  ["squirrel", "animals", ["squirrels"], ["rabbit", "raccoon"]],
  ["swan", "animals", ["swans"], ["duck", "flamingo"]],
  ["tiger", "animals", ["tigers"], ["lion", "zebra"]],
  ["turtle", "animals", ["tortoise"], ["frog", "snail"]],
  ["whale", "animals", ["whales"], ["shark", "dolphin"]],
  ["zebra", "animals", ["zebras"], ["horse", "tiger"]],

  ["anchor", "objects", ["anchors"], ["hook", "boat"]],
  ["backpack", "objects", ["rucksack"], ["suitcase", "handbag"]],
  ["balloon", "objects", ["balloons"], ["bubble", "kite"]],
  ["basket", "objects", ["hamper"], ["bucket", "bag"]],
  ["bathtub", "objects", ["tub"], ["sink", "pool"]],
  ["bell", "objects", ["chime"], ["clock", "drum"]],
  ["bicycle", "objects", ["bike"], ["motorcycle", "unicycle"]],
  ["binoculars", "objects", ["field glasses"], ["telescope", "glasses"]],
  ["book", "objects", ["novel"], ["newspaper", "envelope"]],
  ["bottle", "objects", ["flask"], ["vase", "bucket"]],
  ["broom", "objects", ["brooms"], ["mop", "shovel"]],
  ["bucket", "objects", ["pail"], ["basket", "bottle"]],
  ["camera", "objects", ["cameras"], ["projector", "television"]],
  ["candle", "objects", ["candles"], ["lamp", "campfire"]],
  ["chair", "objects", ["seat"], ["table", "ladder"]],
  ["clock", "objects", ["timepiece"], ["watch", "compass"]],
  ["comb", "objects", ["combs"], ["brush", "fork"]],
  ["compass", "objects", ["compasses"], ["clock", "map"]],
  ["crown", "objects", ["tiara"], ["hat", "helmet"]],
  ["drum", "objects", ["drums"], ["bell", "bucket"]],
  ["envelope", "objects", ["envelopes"], ["book", "mailbox"]],
  ["fan", "objects", ["fans"], ["windmill", "umbrella"]],
  ["flashlight", "objects", ["torch"], ["lamp", "candle"]],
  ["fork", "objects", ["forks"], ["spoon", "rake"]],
  ["guitar", "objects", ["guitars"], ["violin", "banjo"]],
  ["hammer", "objects", ["mallet"], ["axe", "shovel"]],
  ["helmet", "objects", ["helmets"], ["hat", "crown"]],
  ["key", "objects", ["keys"], ["lock", "whistle"]],
  ["kite", "objects", ["kites"], ["balloon", "airplane"]],
  ["ladder", "objects", ["stepladder"], ["stairs", "bridge"]],
  ["lamp", "objects", ["lamps"], ["candle", "flashlight"]],
  ["mailbox", "objects", ["postbox"], ["envelope", "birdhouse"]],
  ["microphone", "objects", ["mic"], ["speaker", "telescope"]],
  ["mirror", "objects", ["looking glass"], ["window", "picture"]],
  ["mug", "objects", ["cup"], ["bowl", "bucket"]],
  ["paintbrush", "objects", ["paint brush"], ["pencil", "broom"]],
  ["pencil", "objects", ["pencils"], ["pen", "paintbrush"]],
  ["piano", "objects", ["pianos"], ["organ", "xylophone"]],
  ["pillow", "objects", ["pillows"], ["blanket", "mattress"]],
  ["scissors", "objects", ["shears"], ["pliers", "fork"]],
  ["shovel", "objects", ["spade"], ["rake", "hammer"]],
  ["skateboard", "objects", ["skate board"], ["surfboard", "scooter"]],
  ["suitcase", "objects", ["luggage"], ["backpack", "briefcase"]],
  ["telescope", "objects", ["spyglass"], ["binoculars", "microscope"]],
  ["toaster", "objects", ["toasters"], ["oven", "television"]],
  ["toothbrush", "objects", ["dental brush"], ["paintbrush", "comb"]],
  ["trumpet", "objects", ["horn"], ["trombone", "flute"]],
  ["umbrella", "objects", ["parasol"], ["kite", "mushroom"]],
  ["vase", "objects", ["flower vase"], ["bottle", "mug"]],
  ["violin", "objects", ["fiddle"], ["guitar", "cello"]],
  ["wagon", "objects", ["cart"], ["car", "wheelbarrow"]],
  ["whistle", "objects", ["whistles"], ["flute", "bell"]],

  ["apple", "food", ["apples"], ["tomato", "orange"]],
  ["banana", "food", ["bananas"], ["lemon", "pepper"]],
  ["burger", "food", ["hamburger"], ["sandwich", "pizza"]],
  ["cake", "food", ["cakes"], ["bread", "pie"]],
  ["carrot", "food", ["carrots"], ["parsnip", "banana"]],
  ["cheese", "food", ["cheeses"], ["cake", "butter"]],
  ["cherry", "food", ["cherries"], ["apple", "grapes"]],
  ["cookie", "food", ["biscuit"], ["cracker", "cake"]],
  ["cupcake", "food", ["cup cake"], ["muffin", "cake"]],
  ["donut", "food", ["doughnut"], ["bagel", "pretzel"]],
  ["egg", "food", ["eggs"], ["potato", "balloon"]],
  ["grapes", "food", ["grape bunch"], ["cherries", "berries"]],
  ["sundae", "food", ["ice cream sundae"], ["cone", "cupcake"]],
  ["lemon", "food", ["lemons"], ["orange", "banana"]],
  ["orange", "food", ["oranges"], ["apple", "lemon"]],
  ["pear", "food", ["pears"], ["apple", "avocado"]],
  ["pizza", "food", ["pizza pie"], ["burger", "cake"]],
  ["popcorn", "food", ["popped corn"], ["rice", "cereal"]],
  ["pretzel", "food", ["pretzels"], ["donut", "bread"]],
  ["sandwich", "food", ["sandwiches"], ["burger", "toast"]],
  ["strawberry", "food", ["strawberries"], ["raspberry", "cherry"]],
  ["watermelon", "food", ["water melon"], ["pumpkin", "orange"]],

  ["cactus", "nature", ["cacti"], ["tree", "flower"]],
  ["cloud", "nature", ["clouds"], ["smoke", "snowflake"]],
  ["flower", "nature", ["blossom"], ["tree", "cactus"]],
  ["igloo", "places", ["snowhouse"], ["tent", "snowman"]],
  ["island", "places", ["isle"], ["mountain", "beach"]],
  ["lighthouse", "places", ["light house"], ["house", "tower"]],
  ["mountain", "nature", ["mountains"], ["volcano", "hill"]],
  ["mushroom", "nature", ["toadstool"], ["umbrella", "flower"]],
  ["rainbow", "nature", ["rainbows"], ["bridge", "cloud"]],
  ["snowflake", "nature", ["snowflakes"], ["star", "flower"]],
  ["snowman", "characters", ["snow figure"], ["snowflake", "person"]],
  ["star", "space", ["stars"], ["sun", "snowflake"]],
  ["sun", "space", ["sunshine"], ["moon", "star"]],
  ["tornado", "nature", ["twister"], ["cloud", "volcano"]],
  ["tree", "nature", ["trees"], ["flower", "cactus"]],
  ["volcano", "nature", ["volcanoes"], ["mountain", "tornado"]],
  ["waterfall", "nature", ["waterfalls"], ["river", "fountain"]],
  ["castle", "places", ["fortress"], ["house", "lighthouse"]],
  ["bridge", "places", ["bridges"], ["tunnel", "road"]],
  ["house", "places", ["home"], ["castle", "barn"]],
  ["windmill", "places", ["wind mill"], ["fan", "lighthouse"]],
  ["barn", "places", ["barns"], ["house", "castle"]],

  ["airplane", "vehicles", ["aeroplane"], ["helicopter", "rocket"]],
  ["ambulance", "vehicles", ["ambulances"], ["firetruck", "car"]],
  ["boat", "vehicles", ["vessel"], ["submarine", "canoe"]],
  ["bus", "vehicles", ["buses"], ["van", "train"]],
  ["canoe", "vehicles", ["canoes"], ["boat", "kayak"]],
  ["car", "vehicles", ["automobile"], ["truck", "bus"]],
  ["helicopter", "vehicles", ["chopper"], ["airplane", "drone"]],
  ["motorcycle", "vehicles", ["motorbike"], ["bicycle", "scooter"]],
  ["rocket", "vehicles", ["rockets"], ["airplane", "missile"]],
  ["submarine", "vehicles", ["submersible"], ["boat", "whale"]],
  ["tractor", "vehicles", ["tractors"], ["truck", "bulldozer"]],
  ["train", "vehicles", ["locomotive"], ["bus", "tram"]],
  ["truck", "vehicles", ["lorry"], ["car", "tractor"]],

  ["alien", "characters", ["extraterrestrial"], ["astronaut", "robot"]],
  ["astronaut", "characters", ["spaceman"], ["alien", "knight"]],
  ["dragon", "characters", ["dragons"], ["dinosaur", "alligator"]],
  ["fairy", "characters", ["sprite"], ["angel", "butterfly"]],
  ["ghost", "characters", ["spirit"], ["mummy", "cloud"]],
  ["knight", "characters", ["armored knight"], ["pirate", "astronaut"]],
  ["mermaid", "characters", ["mermaids"], ["fairy", "dolphin"]],
  ["mummy", "characters", ["mummies"], ["ghost", "zombie"]],
  ["pirate", "characters", ["buccaneer"], ["knight", "sailor"]],
  ["robot", "characters", ["automaton"], ["astronaut", "alien"]],
  ["vampire", "characters", ["vampires"], ["ghost", "wizard"]],
  ["wizard", "characters", ["sorcerer"], ["knight", "vampire"]],

  ["dog", "animals", ["puppy"], ["cat", "wolf"]],
  ["cow", "animals", ["cows"], ["horse", "goat"]],
  ["sheep", "animals", ["lamb"], ["goat", "cow"]],
  ["snake", "animals", ["serpent"], ["worm", "lizard"]],
  ["fish", "animals", ["fishes"], ["whale", "dolphin"]],
  ["lizard", "animals", ["lizards"], ["snake", "frog"]],
  ["mouse", "animals", ["mice"], ["hamster", "rabbit"]],
  ["peacock", "animals", ["peacocks"], ["turkey", "flamingo"]],
  ["parrot", "animals", ["parrots"], ["eagle", "owl"]],
  ["ostrich", "animals", ["ostriches"], ["flamingo", "swan"]],
  ["walrus", "animals", ["walruses"], ["seal", "whale"]],
  ["seahorse", "animals", ["sea horse"], ["fish", "shrimp"]],
  ["starfish", "animals", ["sea star"], ["octopus", "star"]],
  ["caterpillar", "animals", ["caterpillars"], ["worm", "centipede"]],
  ["dinosaur", "animals", ["dino"], ["dragon", "alligator"]],
  ["turkey", "animals", ["turkeys"], ["chicken", "peacock"]],
  ["wolf", "animals", ["wolves"], ["dog", "fox"]],
  ["porcupine", "animals", ["porcupines"], ["hedgehog", "beaver"]],
  ["beaver", "animals", ["beavers"], ["otter", "raccoon"]],
  ["sloth", "animals", ["sloths"], ["monkey", "koala"]],

  ["hat", "clothing", ["cap"], ["helmet", "crown"]],
  ["shirt", "clothing", ["shirts"], ["dress", "jacket"]],
  ["pants", "clothing", ["trousers"], ["shorts", "skirt"]],
  ["shorts", "clothing", ["short pants"], ["pants", "skirt"]],
  ["dress", "clothing", ["gown"], ["skirt", "shirt"]],
  ["skirt", "clothing", ["skirts"], ["dress", "shorts"]],
  ["sock", "clothing", ["socks"], ["shoe", "glove"]],
  ["shoe", "clothing", ["shoes"], ["sock", "boot"]],
  ["boot", "clothing", ["boots"], ["shoe", "sock"]],
  ["glove", "clothing", ["gloves"], ["mitten", "sock"]],
  ["mitten", "clothing", ["mittens"], ["glove", "sock"]],
  ["scarf", "clothing", ["scarves"], ["tie", "belt"]],
  ["belt", "clothing", ["belts"], ["rope", "scarf"]],
  ["tie", "clothing", ["necktie"], ["scarf", "ribbon"]],
  ["jacket", "clothing", ["coat"], ["shirt", "dress"]],
  ["sunglasses", "clothing", ["shades"], ["goggles", "binoculars"]],
  ["necklace", "clothing", ["necklaces"], ["bracelet", "belt"]],
  ["bracelet", "clothing", ["bangle"], ["necklace", "ring"]],
  ["ring", "clothing", ["rings"], ["bracelet", "donut"]],
  ["watch", "clothing", ["wristwatch"], ["clock", "bracelet"]],

  ["table", "objects", ["tables"], ["chair", "bed"]],
  ["bed", "objects", ["beds"], ["sofa", "table"]],
  ["sofa", "objects", ["couch"], ["bed", "chair"]],
  ["door", "objects", ["doors"], ["window", "gate"]],
  ["window", "objects", ["windows"], ["door", "mirror"]],
  ["spoon", "objects", ["spoons"], ["fork", "ladle"]],
  ["bowl", "objects", ["bowls"], ["plate", "mug"]],
  ["plate", "objects", ["plates"], ["bowl", "frisbee"]],
  ["teapot", "objects", ["tea pot"], ["kettle", "watering can"]],
  ["kettle", "objects", ["kettles"], ["teapot", "pot"]],
  ["skillet", "objects", ["frying pan"], ["pot", "plate"]],
  ["oven", "objects", ["ovens"], ["microwave", "toaster"]],
  ["refrigerator", "objects", ["fridge"], ["oven", "wardrobe"]],
  ["microwave", "objects", ["microwave oven"], ["toaster", "television"]],
  ["television", "objects", ["tv"], ["computer", "microwave"]],
  ["laptop", "objects", ["notebook computer"], ["television", "tablet"]],
  ["telephone", "objects", ["phone"], ["radio", "calculator"]],
  ["radio", "objects", ["radios"], ["television", "telephone"]],
  ["headphones", "objects", ["headset"], ["earmuffs", "microphone"]],
  ["keyboard", "objects", ["computer keyboard"], ["piano", "calculator"]],
  ["calculator", "objects", ["calculators"], ["telephone", "keyboard"]],
  ["briefcase", "objects", ["attache case"], ["suitcase", "backpack"]],
  ["wallet", "objects", ["billfold"], ["purse", "envelope"]],
  ["tent", "objects", ["tents"], ["igloo", "house"]],
  ["hammock", "objects", ["hammocks"], ["swing", "bed"]],
  ["swing", "objects", ["swings"], ["hammock", "seesaw"]],
  ["seesaw", "objects", ["teeter totter"], ["swing", "slide"]],
  ["slide", "objects", ["playground slide"], ["ladder", "seesaw"]],
  ["wheelbarrow", "objects", ["wheel barrow"], ["wagon", "bucket"]],
  ["rake", "objects", ["rakes"], ["broom", "shovel"]],
  ["mop", "objects", ["mops"], ["broom", "paintbrush"]],
  ["saw", "objects", ["handsaw"], ["knife", "rake"]],
  ["wrench", "objects", ["spanner"], ["pliers", "hammer"]],
  ["pliers", "objects", ["pincers"], ["scissors", "wrench"]],
  ["screwdriver", "objects", ["screw driver"], ["hammer", "pencil"]],
  ["lock", "objects", ["padlock"], ["key", "bell"]],
  ["magnet", "objects", ["magnets"], ["horseshoe", "rainbow"]],
  ["parachute", "objects", ["parachutes"], ["umbrella", "balloon"]],
  ["trampoline", "objects", ["trampolines"], ["pool", "bed"]],
  ["trophy", "objects", ["trophies"], ["vase", "goblet"]],
  ["soap", "objects", ["bar of soap"], ["sponge", "candle"]],
  ["sponge", "objects", ["sponges"], ["soap", "cheese"]],
  ["toilet", "objects", ["lavatory"], ["sink", "bathtub"]],
  ["sink", "objects", ["washbasin"], ["bathtub", "toilet"]],
  ["stamp", "objects", ["postage stamp"], ["envelope", "sticker"]],
  ["dice", "objects", ["die"], ["domino", "marble"]],

  ["avocado", "food", ["avocados"], ["pear", "mango"]],
  ["pineapple", "food", ["pineapples"], ["coconut", "melon"]],
  ["coconut", "food", ["coconuts"], ["pineapple", "potato"]],
  ["peach", "food", ["peaches"], ["apple", "orange"]],
  ["pumpkin", "food", ["pumpkins"], ["watermelon", "orange"]],
  ["tomato", "food", ["tomatoes"], ["apple", "pepper"]],
  ["potato", "food", ["potatoes"], ["egg", "carrot"]],
  ["broccoli", "food", ["broccoli floret"], ["tree", "cauliflower"]],
  ["corn", "food", ["maize"], ["banana", "carrot"]],
  ["onion", "food", ["onions"], ["garlic", "turnip"]],
  ["pepper", "food", ["bell pepper"], ["tomato", "pear"]],
  ["bread", "food", ["loaf"], ["cake", "sandwich"]],
  ["pie", "food", ["pies"], ["cake", "pizza"]],
  ["taco", "food", ["tacos"], ["sandwich", "burrito"]],
  ["spaghetti", "food", ["spaghetti noodles"], ["worms", "rice"]],
  ["pancake", "food", ["pancakes"], ["waffle", "pizza"]],
  ["waffle", "food", ["waffles"], ["pancake", "toast"]],
  ["lollipop", "food", ["lollypop"], ["balloon", "ice cream"]],
  ["popsicle", "food", ["ice lolly"], ["lollipop", "ice cream"]],
  ["croissant", "food", ["croissants"], ["bread", "banana"]],

  ["moon", "space", ["crescent moon"], ["sun", "banana"]],
  ["planet", "space", ["planets"], ["moon", "star"]],
  ["comet", "space", ["comets"], ["planet", "rocket"]],
  ["leaf", "nature", ["leaves"], ["feather", "flower"]],
  ["acorn", "nature", ["acorns"], ["pinecone", "mushroom"]],
  ["pinecone", "nature", ["pine cone"], ["acorn", "pineapple"]],
  ["feather", "nature", ["feathers"], ["leaf", "paintbrush"]],
  ["seashell", "nature", ["sea shell"], ["snail", "fan"]],
  ["lightning", "nature", ["lightning bolt"], ["branch", "arrow"]],
  ["campfire", "nature", ["camp fire"], ["volcano", "candle"]],
  ["fountain", "places", ["fountains"], ["waterfall", "sprinkler"]],
  ["pyramid", "places", ["pyramids"], ["mountain", "tent"]],
  ["sailboat", "vehicles", ["sailing boat"], ["canoe", "yacht"]],
  ["scooter", "vehicles", ["scooters"], ["bicycle", "skateboard"]],
  ["unicycle", "vehicles", ["unicycles"], ["bicycle", "wheel"]],
  ["firetruck", "vehicles", ["fire engine"], ["ambulance", "bus"]],
  ["bulldozer", "vehicles", ["dozer"], ["tractor", "truck"]],
  ["sled", "vehicles", ["sledge"], ["wagon", "skateboard"]],
  ["unicorn", "characters", ["unicorns"], ["horse", "dragon"]],
  ["clown", "characters", ["clowns"], ["jester", "magician"]],
] as const satisfies readonly PromptSeed[];

// Hard prompts ask for one visible action. Aliases keep that action intact:
// naming only the prop ("kite") must not solve "flying a kite".
const ACTION_PROMPT_SEEDS = [
  ["flying a kite", "outdoor actions", ["fly a kite", "kite flying"], ["kite", "holding a kite", "flying an airplane"]],
  ["riding a bicycle", "outdoor actions", ["ride a bicycle", "riding a bike", "bike riding"], ["bicycle", "carrying a bicycle"]],
  ["walking a dog", "outdoor actions", ["walk a dog", "dog walking"], ["dog", "feeding a dog"]],
  ["planting a tree", "outdoor actions", ["plant a tree", "tree planting"], ["tree", "climbing a tree"]],
  ["watering flowers", "outdoor actions", ["water flowers", "watering plants"], ["flowers", "picking flowers"]],
  ["building a sandcastle", "outdoor actions", ["build a sandcastle", "making a sandcastle"], ["sandcastle", "destroying a sandcastle"]],
  ["climbing a tree", "outdoor actions", ["climb a tree", "tree climbing"], ["tree", "chopping a tree"]],
  ["pitching a tent", "outdoor actions", ["pitch a tent", "putting up a tent", "setting up a tent"], ["tent", "sleeping in a tent"]],
  ["roasting marshmallows", "outdoor actions", ["roast marshmallows", "toasting marshmallows"], ["marshmallows", "burning wood"]],
  ["skipping stones", "outdoor actions", ["skip stones", "skimming stones"], ["stones", "collecting stones"]],
  ["catching a butterfly", "outdoor actions", ["catch a butterfly", "catching butterflies"], ["butterfly", "watching butterflies"]],
  ["picking apples", "outdoor actions", ["pick apples", "apple picking"], ["apples", "eating apples"]],
  ["raking leaves", "outdoor actions", ["rake leaves", "leaf raking"], ["leaves", "sweeping the floor"]],
  ["mowing the lawn", "outdoor actions", ["mow the lawn", "cutting the grass", "lawn mowing"], ["lawn", "watering the lawn"]],
  ["shoveling snow", "outdoor actions", ["shovel snow", "shovelling snow"], ["snow", "building a snowman"]],
  ["building a snowman", "outdoor actions", ["build a snowman", "making a snowman"], ["snowman", "melting a snowman"]],
  ["throwing a snowball", "outdoor actions", ["throw a snowball", "snowball throwing"], ["snowball", "making a snowball"]],
  ["jumping in puddles", "outdoor actions", ["jump in puddles", "splashing in puddles"], ["puddles", "walking in the rain"]],
  ["digging a hole", "outdoor actions", ["dig a hole", "digging with a shovel"], ["hole", "climbing out of a hole"]],
  ["feeding ducks", "outdoor actions", ["feed ducks", "feeding a duck"], ["ducks", "chasing ducks"]],

  ["driving a car", "travel actions", ["drive a car", "car driving", "driving an automobile"], ["car", "washing a car"]],
  ["rowing a boat", "travel actions", ["row a boat", "rowing with oars"], ["boat", "sailing a boat"]],
  ["sailing a boat", "travel actions", ["sail a boat", "sailing a sailboat"], ["boat", "rowing a boat"]],
  ["flying an airplane", "travel actions", ["fly an airplane", "flying a plane", "piloting an airplane"], ["airplane", "flying a kite"]],
  ["riding a horse", "travel actions", ["ride a horse", "horse riding", "horseback riding"], ["horse", "feeding a horse"]],
  ["riding a scooter", "travel actions", ["ride a scooter", "scooter riding"], ["scooter", "carrying a scooter"]],
  ["riding a skateboard", "travel actions", ["ride a skateboard", "skateboarding"], ["skateboard", "carrying a skateboard"]],
  ["paddling a kayak", "travel actions", ["paddle a kayak", "kayaking"], ["kayak", "sailing a boat"]],
  ["pulling a wagon", "travel actions", ["pull a wagon", "pulling a cart"], ["wagon", "riding in a wagon"]],
  ["pushing a stroller", "travel actions", ["push a stroller", "pushing a pram"], ["stroller", "carrying a baby"]],
  ["packing a suitcase", "travel actions", ["pack a suitcase", "suitcase packing"], ["suitcase", "carrying a suitcase"]],
  ["carrying an umbrella", "travel actions", ["carry an umbrella", "holding an umbrella"], ["umbrella", "closing an umbrella"]],
  ["rolling a suitcase", "travel actions", ["roll a suitcase", "pulling a suitcase"], ["suitcase", "packing a suitcase"]],
  ["boarding a bus", "travel actions", ["board a bus", "getting on a bus"], ["bus", "driving a bus"]],
  ["pumping a bicycle tire", "travel actions", ["pump a bicycle tire", "inflating a bike tire"], ["bicycle", "riding a bicycle"]],

  ["kicking a soccer ball", "sports actions", ["kick a soccer ball", "kicking a football"], ["soccer ball", "throwing a soccer ball"]],
  ["shooting a basketball", "sports actions", ["shoot a basketball", "shooting hoops", "throwing a basketball into a hoop"], ["basketball", "kicking a basketball"]],
  ["swinging a baseball bat", "sports actions", ["swing a baseball bat", "hitting a baseball"], ["baseball bat", "throwing a baseball"]],
  ["playing tennis", "sports actions", ["play tennis", "hitting a tennis ball"], ["tennis ball", "playing golf"]],
  ["playing golf", "sports actions", ["play golf", "hitting a golf ball"], ["golf club", "playing tennis"]],
  ["bowling a ball", "sports actions", ["bowl a ball", "tenpin bowling"], ["ball", "playing basketball"]],
  ["jumping rope", "sports actions", ["skipping rope", "skipping with a rope", "jumping over a rope"], ["rope", "jump rope", "tying a rope"]],
  ["lifting weights", "sports actions", ["lift weights", "weight lifting", "weightlifting"], ["weights", "carrying a suitcase"]],
  ["doing a cartwheel", "sports actions", ["do a cartwheel", "performing a cartwheel"], ["cartwheel", "doing pushups"]],
  ["doing pushups", "sports actions", ["do pushups", "doing push ups"], ["pushup", "doing situps"]],
  ["doing a handstand", "sports actions", ["do a handstand", "standing on hands"], ["handstand", "standing on your head"]],
  ["ice skating", "sports actions", ["skating on ice", "skating across ice"], ["ice", "ice skate", "ice skates", "roller skating"]],
  ["roller skating", "sports actions", ["skating on roller skates", "skating with roller skates"], ["roller skate", "roller skates", "ice skating"]],
  ["skiing downhill", "sports actions", ["ski downhill", "downhill skiing"], ["skis", "skateboarding"]],
  ["snowboarding downhill", "sports actions", ["snowboard downhill", "downhill snowboarding"], ["snowboard", "skiing downhill"]],
  ["surfing a wave", "sports actions", ["surf a wave", "riding a wave on a surfboard"], ["surfboard", "swimming in the ocean"]],
  ["swimming in a pool", "sports actions", ["swim in a pool", "swimming laps"], ["pool", "diving into a pool"]],
  ["diving into a pool", "sports actions", ["dive into a pool", "jumping into a pool"], ["pool", "swimming laps"]],
  ["climbing a rock wall", "sports actions", ["climb a rock wall", "rock climbing"], ["wall", "climbing a tree"]],
  ["shooting an arrow", "sports actions", ["shoot an arrow", "using a bow and arrow", "archery"], ["arrow", "throwing a spear"]],

  ["baking a cake", "kitchen actions", ["bake a cake", "making a cake"], ["cake", "eating a cake"]],
  ["decorating a cupcake", "kitchen actions", ["decorate a cupcake", "icing a cupcake"], ["cupcake", "eating a cupcake"]],
  ["flipping a pancake", "kitchen actions", ["flip a pancake", "tossing a pancake"], ["pancake", "eating a pancake"]],
  ["rolling out dough", "kitchen actions", ["roll out dough", "rolling dough with a rolling pin"], ["dough", "kneading dough"]],
  ["kneading bread", "kitchen actions", ["knead bread", "kneading dough"], ["bread", "slicing bread"]],
  ["cracking an egg", "kitchen actions", ["crack an egg", "breaking an egg"], ["egg", "frying an egg"]],
  ["frying an egg", "kitchen actions", ["fry an egg", "cooking an egg in a pan"], ["egg", "cracking an egg"]],
  ["stirring soup", "kitchen actions", ["stir soup", "mixing soup"], ["soup", "eating soup"]],
  ["chopping vegetables", "kitchen actions", ["chop vegetables", "cutting vegetables"], ["vegetables", "washing vegetables"]],
  ["peeling a banana", "kitchen actions", ["peel a banana", "taking the peel off a banana"], ["banana", "eating a banana"]],
  ["slicing bread", "kitchen actions", ["slice bread", "cutting bread"], ["bread", "kneading bread"]],
  ["making a sandwich", "kitchen actions", ["make a sandwich", "preparing a sandwich"], ["sandwich", "eating a sandwich"]],
  ["pouring milk", "kitchen actions", ["pour milk", "pouring a glass of milk"], ["milk", "drinking milk"]],
  ["squeezing a lemon", "kitchen actions", ["squeeze a lemon", "juicing a lemon"], ["lemon", "peeling a lemon"]],
  ["blending a smoothie", "kitchen actions", ["blend a smoothie", "making a smoothie"], ["smoothie", "drinking a smoothie"]],
  ["eating spaghetti", "kitchen actions", ["eat spaghetti", "eating noodles"], ["spaghetti", "cooking spaghetti"]],
  ["eating ice cream", "kitchen actions", ["eat ice cream", "licking ice cream"], ["ice cream", "making ice cream"]],
  ["blowing out candles", "kitchen actions", ["blow out candles", "blowing out birthday candles"], ["candles", "lighting candles"]],
  ["washing dishes", "kitchen actions", ["wash dishes", "doing the dishes"], ["dishes", "drying dishes"]],
  ["setting the table", "kitchen actions", ["set the table", "laying the table"], ["table", "cleaning the table"]],

  ["sweeping the floor", "household actions", ["sweep the floor", "sweeping with a broom"], ["broom", "mopping the floor"]],
  ["mopping the floor", "household actions", ["mop the floor", "mopping with a mop"], ["mop", "sweeping the floor"]],
  ["vacuuming a carpet", "household actions", ["vacuum a carpet", "vacuuming the floor"], ["vacuum", "sweeping a carpet"]],
  ["dusting a shelf", "household actions", ["dust a shelf", "dusting shelves"], ["shelf", "painting a shelf"]],
  ["making the bed", "household actions", ["make the bed", "tidying the bed"], ["bed", "sleeping in a bed"]],
  ["folding laundry", "household actions", ["fold laundry", "folding clothes"], ["laundry", "washing clothes"]],
  ["hanging laundry", "household actions", ["hang laundry", "hanging clothes to dry"], ["clothes", "folding laundry"]],
  ["ironing a shirt", "household actions", ["iron a shirt", "ironing clothes"], ["shirt", "folding a shirt"]],
  ["washing a window", "household actions", ["wash a window", "cleaning windows"], ["window", "opening a window"]],
  ["painting a wall", "household actions", ["paint a wall", "painting walls"], ["wall", "washing a wall"]],
  ["hammering a nail", "household actions", ["hammer a nail", "driving a nail with a hammer"], ["hammer", "pulling out a nail"]],
  ["screwing in a screw", "household actions", ["screw in a screw", "tightening a screw"], ["screwdriver", "hammering a nail"]],
  ["changing a lightbulb", "household actions", ["change a lightbulb", "replacing a light bulb"], ["lightbulb", "switching off a light"]],
  ["unclogging a toilet", "household actions", ["unclog a toilet", "using a plunger"], ["toilet", "cleaning a toilet"]],
  ["wrapping a present", "household actions", ["wrap a present", "gift wrapping"], ["present", "opening a present"]],
  ["opening a present", "household actions", ["open a present", "unwrapping a gift"], ["present", "wrapping a present"]],
  ["tying shoelaces", "household actions", ["tie shoelaces", "tying shoes"], ["shoes", "untying shoes"]],
  ["brushing teeth", "household actions", ["brush teeth", "brushing your teeth", "tooth brushing"], ["toothbrush", "brushing hair"]],
  ["brushing hair", "household actions", ["brush hair", "brushing your hair"], ["hair", "brushing teeth"]],
  ["washing hands", "household actions", ["wash hands", "washing your hands"], ["hands", "clapping hands"]],

  ["painting a picture", "creative actions", ["paint a picture", "painting on a canvas"], ["picture", "drawing with a pencil"]],
  ["drawing with a pencil", "creative actions", ["draw with a pencil", "sketching with a pencil"], ["pencil", "painting a wall"]],
  ["taking a photograph", "creative actions", ["take a photograph", "taking a picture", "using a camera"], ["camera", "painting a picture"]],
  ["playing a guitar", "creative actions", ["play a guitar", "strumming a guitar"], ["guitar", "carrying a guitar"]],
  ["playing a piano", "creative actions", ["play a piano", "piano playing"], ["piano", "playing a guitar"]],
  ["playing a violin", "creative actions", ["play a violin", "playing the fiddle"], ["violin", "playing a guitar"]],
  ["beating a drum", "creative actions", ["beat a drum", "playing the drums", "drumming"], ["drum", "carrying a drum"]],
  ["blowing a trumpet", "creative actions", ["blow a trumpet", "playing a trumpet"], ["trumpet", "playing a flute"]],
  ["singing into a microphone", "creative actions", ["sing into a microphone", "singing on a microphone"], ["microphone", "talking on a telephone"]],
  ["conducting an orchestra", "creative actions", ["conduct an orchestra", "orchestra conducting"], ["orchestra", "playing a piano"]],
  ["knitting a scarf", "creative actions", ["knit a scarf", "knitting with needles"], ["scarf", "sewing a button"]],
  ["sewing on a button", "creative actions", ["sew on a button", "sewing a button"], ["button", "knitting a scarf"]],
  ["folding a paper airplane", "creative actions", ["fold a paper airplane", "making a paper plane"], ["airplane", "flying an airplane"]],
  ["cutting paper with scissors", "creative actions", ["cut paper with scissors", "cutting out paper shapes"], ["scissors", "folding paper"]],
  ["sculpting a clay pot", "creative actions", ["sculpt a clay pot", "making pottery", "throwing pottery"], ["pot", "painting a pot"]],

  ["reading a book", "everyday actions", ["read a book", "book reading"], ["book", "writing a book"]],
  ["writing a letter", "everyday actions", ["write a letter", "writing with a pen"], ["letter", "reading a letter"]],
  ["mailing a letter", "everyday actions", ["mail a letter", "posting a letter"], ["letter", "writing a letter"]],
  ["answering a telephone", "everyday actions", ["answer a telephone", "talking on the phone", "making a phone call"], ["telephone", "taking a photograph"]],
  ["looking through binoculars", "everyday actions", ["look through binoculars", "using binoculars"], ["binoculars", "looking through a telescope"]],
  ["looking through a telescope", "everyday actions", ["look through a telescope", "using a telescope"], ["telescope", "using binoculars"]],
  ["sleeping in a hammock", "everyday actions", ["sleep in a hammock", "napping in a hammock"], ["hammock", "pushing a swing"]],
  ["pushing a swing", "everyday actions", ["push a swing", "pushing someone on a swing"], ["swing", "sitting on a swing"]],
  ["sliding down a slide", "everyday actions", ["slide down a slide", "going down a playground slide"], ["slide", "climbing a ladder"]],
  ["bouncing on a trampoline", "everyday actions", ["bounce on a trampoline", "jumping on a trampoline"], ["trampoline", "jumping rope"]],
  ["blowing bubbles", "everyday actions", ["blow bubbles", "making soap bubbles"], ["bubbles", "blowing up a balloon"]],
  ["inflating a balloon", "everyday actions", ["inflate a balloon", "blowing up a balloon"], ["balloon", "popping a balloon"]],
  ["juggling balls", "everyday actions", ["juggle balls", "juggling three balls"], ["balls", "throwing one ball"]],
  ["walking a tightrope", "everyday actions", ["walk a tightrope", "tightrope walking"], ["rope", "jumping rope"]],
  ["searching with a flashlight", "everyday actions", ["search with a flashlight", "looking around with a torch"], ["flashlight", "holding a candle"]],

  ["bathing a dog", "animal actions", ["bathe a dog", "washing a dog"], ["dog", "walking a dog"]],
  ["feeding a cat", "animal actions", ["feed a cat", "giving food to a cat"], ["cat", "petting a cat"]],
  ["milking a cow", "animal actions", ["milk a cow", "cow milking"], ["cow", "feeding a cow"]],
  ["shearing a sheep", "animal actions", ["shear a sheep", "sheep shearing"], ["sheep", "feeding a sheep"]],
  ["catching a fish", "animal actions", ["catch a fish", "fishing with a rod"], ["fish", "feeding a fish"]],
  ["collecting eggs", "animal actions", ["collect eggs", "gathering eggs"], ["eggs", "cracking an egg"]],
  ["grooming a horse", "animal actions", ["groom a horse", "brushing a horse"], ["horse", "riding a horse"]],
  ["walking on stilts", "everyday actions", ["walk on stilts", "stilt walking"], ["stilts", "walking a tightrope"]],
  ["dancing ballet", "creative actions", ["dance ballet", "ballet dancing", "performing ballet"], ["ballet", "ice skating"]],
  ["waving goodbye", "everyday actions", ["wave goodbye", "waving farewell", "waving to someone"], ["hand", "clapping hands"]],
  ["climbing a ladder", "household actions", ["climb a ladder", "going up a ladder"], ["ladder", "carrying a ladder"]],
  ["balancing a book on your head", "everyday actions", ["balance a book on your head", "balancing books on your head"], ["book", "reading a book"]],
  ["decorating a christmas tree", "creative actions", ["decorate a christmas tree", "putting ornaments on a tree"], ["christmas tree", "planting a tree"]],
  ["carving a pumpkin", "creative actions", ["carve a pumpkin", "making a jack o lantern"], ["pumpkin", "painting a pumpkin"]],
  ["hanging a picture", "household actions", ["hang a picture", "putting a picture on a wall"], ["picture", "painting a picture"]],
] as const satisfies readonly PromptSeed[];

const SINGLE_WORD_PRACTICE_EXCLUSIONS = new Set<string>([
  "ant", "bat", "beetle", "donkey", "hamster", "hedgehog", "jellyfish",
  "ladybug", "lobster", "raccoon", "rhinoceros", "scorpion", "snail", "swan",
  "anchor", "binoculars", "comb", "compass", "envelope", "fan", "paintbrush",
  "whistle", "cheese", "cherry", "grapes", "pretzel", "snowflake", "windmill",
  "ambulance", "canoe", "alien", "fairy", "knight", "mummy", "vampire",
]);

export const PROMPT_DECK: readonly PromptCard[] = SINGLE_WORD_PROMPT_SEEDS.map(
  ([prompt, category, aliases, rejectedAnswers]) => ({
    prompt,
    category,
    difficulty: "easy",
    aliases,
    rejectedAnswers,
    practiceEligible: !SINGLE_WORD_PRACTICE_EXCLUSIONS.has(prompt),
  }),
);

export const EASY_PROMPTS = PROMPT_DECK;

export const PRACTICE_PROMPTS: readonly PromptCard[] = PROMPT_DECK.filter(
  (prompt) => prompt.practiceEligible,
);

export const HARD_PROMPTS: readonly PromptCard[] = ACTION_PROMPT_SEEDS.map(
  ([prompt, category, aliases, rejectedAnswers]) => ({
    prompt,
    category,
    difficulty: "hard",
    aliases,
    rejectedAnswers,
    practiceEligible: true,
  }),
);

export function randomPrompt(
  usedPrompts: Iterable<string> | string = [],
  practice = false,
  difficulty: PromptDifficulty = "easy",
): PromptCard {
  const deck = difficulty === "hard" ? HARD_PROMPTS : practice ? PRACTICE_PROMPTS : PROMPT_DECK;
  const used = new Set(typeof usedPrompts === "string" ? [usedPrompts] : usedPrompts);
  const available = deck.filter((card) => !used.has(card.prompt));
  const candidates = available.length > 0 ? available : deck;
  const random = crypto.getRandomValues(new Uint32Array(1))[0] ?? 0;
  const index = random % candidates.length;
  return candidates[index] ?? deck[0]!;
}
