export interface PromptCard {
  readonly prompt: string;
  readonly category: string;
  readonly aliases: readonly string[];
  /** Visually plausible but incorrect guesses that must not score. */
  readonly rejectedAnswers: readonly string[];
  readonly practiceEligible: boolean;
}

type PromptSeed = readonly [
  prompt: string,
  category: string,
  aliases: readonly string[],
  rejectedAnswers: readonly string[],
];

// Canonical prompts are deliberately concrete, visually distinct, single-word nouns.
// Alternate regional names, spellings, and common plurals live only in aliases.
const SINGLE_WORD_PROMPT_SEEDS = [
  ["alligator", "animals", ["gator"], ["snake", "shark"]],
  ["ant", "animals", ["ants"], ["spider", "bee"]],
  ["bat", "animals", ["bats"], ["bird", "butterfly"]],
  ["bear", "animals", ["bears"], ["lion", "gorilla"]],
  ["bee", "animals", ["honeybee"], ["fly", "butterfly"]],
  ["beetle", "animals", ["beetles"], ["bee", "spider"]],
  ["butterfly", "animals", ["butterflies"], ["bird", "dragonfly"]],
  ["camel", "animals", ["camels"], ["horse", "giraffe"]],
  ["cat", "animals", ["kitty"], ["dog", "rabbit"]],
  ["chicken", "animals", ["hen"], ["duck", "turkey"]],
  ["crab", "animals", ["crabs"], ["spider", "lobster"]],
  ["deer", "animals", ["stag"], ["horse", "goat"]],
  ["dolphin", "animals", ["dolphins"], ["shark", "whale"]],
  ["donkey", "animals", ["burro"], ["horse", "goat"]],
  ["duck", "animals", ["duckling"], ["swan", "chicken"]],
  ["eagle", "animals", ["eagles"], ["owl", "bat"]],
  ["elephant", "animals", ["elephants"], ["hippo", "rhinoceros"]],
  ["flamingo", "animals", ["flamingos"], ["swan", "ostrich"]],
  ["fox", "animals", ["foxes"], ["cat", "wolf"]],
  ["frog", "animals", ["frogs"], ["turtle", "lizard"]],
  ["giraffe", "animals", ["giraffes"], ["camel", "horse"]],
  ["goat", "animals", ["goats"], ["sheep", "deer"]],
  ["gorilla", "animals", ["gorillas"], ["bear", "monkey"]],
  ["hamster", "animals", ["hamsters"], ["mouse", "rabbit"]],
  ["hedgehog", "animals", ["hedgehogs"], ["porcupine", "mouse"]],
  ["hippo", "animals", ["hippopotamus"], ["rhinoceros", "elephant"]],
  ["horse", "animals", ["stallion"], ["donkey", "cow"]],
  ["jellyfish", "animals", ["jelly fish"], ["octopus", "squid"]],
  ["kangaroo", "animals", ["kangaroos"], ["rabbit", "deer"]],
  ["koala", "animals", ["koalas"], ["panda", "bear"]],
  ["ladybug", "animals", ["ladybird"], ["beetle", "butterfly"]],
  ["lion", "animals", ["lions"], ["tiger", "bear"]],
  ["lobster", "animals", ["lobsters"], ["crab", "shrimp"]],
  ["monkey", "animals", ["monkeys"], ["gorilla", "bear"]],
  ["octopus", "animals", ["octopuses"], ["jellyfish", "spider"]],
  ["owl", "animals", ["owls"], ["eagle", "penguin"]],
  ["panda", "animals", ["pandas"], ["bear", "koala"]],
  ["penguin", "animals", ["penguins"], ["duck", "owl"]],
  ["pig", "animals", ["piglet"], ["hippo", "cow"]],
  ["rabbit", "animals", ["bunny"], ["cat", "hamster"]],
  ["raccoon", "animals", ["racoons"], ["cat", "fox"]],
  ["rhinoceros", "animals", ["rhino"], ["elephant", "hippo"]],
  ["scorpion", "animals", ["scorpions"], ["lobster", "spider"]],
  ["seal", "animals", ["seals"], ["dolphin", "penguin"]],
  ["shark", "animals", ["sharks"], ["whale", "dolphin"]],
  ["snail", "animals", ["snails"], ["turtle", "worm"]],
  ["spider", "animals", ["spiders"], ["ant", "scorpion"]],
  ["squirrel", "animals", ["squirrels"], ["rabbit", "raccoon"]],
  ["swan", "animals", ["swans"], ["duck", "flamingo"]],
  ["tiger", "animals", ["tigers"], ["lion", "zebra"]],
  ["turtle", "animals", ["tortoise"], ["frog", "snail"]],
  ["whale", "animals", ["whales"], ["shark", "dolphin"]],
  ["zebra", "animals", ["zebras"], ["horse", "tiger"]],

  ["anchor", "objects", ["anchors"], ["hook", "boat"]],
  ["backpack", "objects", ["rucksack"], ["suitcase", "handbag"]],
  ["balloon", "objects", ["balloons"], ["bubble", "kite"]],
  ["basket", "objects", ["hamper"], ["bucket", "bag"]],
  ["bathtub", "objects", ["tub"], ["sink", "pool"]],
  ["bell", "objects", ["chime"], ["clock", "drum"]],
  ["bicycle", "objects", ["bike"], ["motorcycle", "unicycle"]],
  ["binoculars", "objects", ["field glasses"], ["telescope", "glasses"]],
  ["book", "objects", ["novel"], ["newspaper", "envelope"]],
  ["bottle", "objects", ["flask"], ["vase", "bucket"]],
  ["broom", "objects", ["brooms"], ["mop", "shovel"]],
  ["bucket", "objects", ["pail"], ["basket", "bottle"]],
  ["camera", "objects", ["cameras"], ["projector", "television"]],
  ["candle", "objects", ["candles"], ["lamp", "campfire"]],
  ["chair", "objects", ["seat"], ["table", "ladder"]],
  ["clock", "objects", ["timepiece"], ["watch", "compass"]],
  ["comb", "objects", ["combs"], ["brush", "fork"]],
  ["compass", "objects", ["compasses"], ["clock", "map"]],
  ["crown", "objects", ["tiara"], ["hat", "helmet"]],
  ["drum", "objects", ["drums"], ["bell", "bucket"]],
  ["envelope", "objects", ["envelopes"], ["book", "mailbox"]],
  ["fan", "objects", ["fans"], ["windmill", "umbrella"]],
  ["flashlight", "objects", ["torch"], ["lamp", "candle"]],
  ["fork", "objects", ["forks"], ["spoon", "rake"]],
  ["guitar", "objects", ["guitars"], ["violin", "banjo"]],
  ["hammer", "objects", ["mallet"], ["axe", "shovel"]],
  ["helmet", "objects", ["helmets"], ["hat", "crown"]],
  ["key", "objects", ["keys"], ["lock", "whistle"]],
  ["kite", "objects", ["kites"], ["balloon", "airplane"]],
  ["ladder", "objects", ["stepladder"], ["stairs", "bridge"]],
  ["lamp", "objects", ["lamps"], ["candle", "flashlight"]],
  ["mailbox", "objects", ["postbox"], ["envelope", "birdhouse"]],
  ["microphone", "objects", ["mic"], ["speaker", "telescope"]],
  ["mirror", "objects", ["looking glass"], ["window", "picture"]],
  ["mug", "objects", ["cup"], ["bowl", "bucket"]],
  ["paintbrush", "objects", ["paint brush"], ["pencil", "broom"]],
  ["pencil", "objects", ["pencils"], ["pen", "paintbrush"]],
  ["piano", "objects", ["pianos"], ["organ", "xylophone"]],
  ["pillow", "objects", ["pillows"], ["blanket", "mattress"]],
  ["scissors", "objects", ["shears"], ["pliers", "fork"]],
  ["shovel", "objects", ["spade"], ["rake", "hammer"]],
  ["skateboard", "objects", ["skate board"], ["surfboard", "scooter"]],
  ["suitcase", "objects", ["luggage"], ["backpack", "briefcase"]],
  ["telescope", "objects", ["spyglass"], ["binoculars", "microscope"]],
  ["toaster", "objects", ["toasters"], ["oven", "television"]],
  ["toothbrush", "objects", ["dental brush"], ["paintbrush", "comb"]],
  ["trumpet", "objects", ["horn"], ["trombone", "flute"]],
  ["umbrella", "objects", ["parasol"], ["kite", "mushroom"]],
  ["vase", "objects", ["flower vase"], ["bottle", "mug"]],
  ["violin", "objects", ["fiddle"], ["guitar", "cello"]],
  ["wagon", "objects", ["cart"], ["car", "wheelbarrow"]],
  ["whistle", "objects", ["whistles"], ["flute", "bell"]],

  ["apple", "food", ["apples"], ["tomato", "orange"]],
  ["banana", "food", ["bananas"], ["lemon", "pepper"]],
  ["burger", "food", ["hamburger"], ["sandwich", "pizza"]],
  ["cake", "food", ["cakes"], ["bread", "pie"]],
  ["carrot", "food", ["carrots"], ["parsnip", "banana"]],
  ["cheese", "food", ["cheeses"], ["cake", "butter"]],
  ["cherry", "food", ["cherries"], ["apple", "grapes"]],
  ["cookie", "food", ["biscuit"], ["cracker", "cake"]],
  ["cupcake", "food", ["cup cake"], ["muffin", "cake"]],
  ["donut", "food", ["doughnut"], ["bagel", "pretzel"]],
  ["egg", "food", ["eggs"], ["potato", "balloon"]],
  ["grapes", "food", ["grape bunch"], ["cherries", "berries"]],
  ["sundae", "food", ["ice cream sundae"], ["cone", "cupcake"]],
  ["lemon", "food", ["lemons"], ["orange", "banana"]],
  ["orange", "food", ["oranges"], ["apple", "lemon"]],
  ["pear", "food", ["pears"], ["apple", "avocado"]],
  ["pizza", "food", ["pizza pie"], ["burger", "cake"]],
  ["popcorn", "food", ["popped corn"], ["rice", "cereal"]],
  ["pretzel", "food", ["pretzels"], ["donut", "bread"]],
  ["sandwich", "food", ["sandwiches"], ["burger", "toast"]],
  ["strawberry", "food", ["strawberries"], ["raspberry", "cherry"]],
  ["watermelon", "food", ["water melon"], ["pumpkin", "orange"]],

  ["cactus", "nature", ["cacti"], ["tree", "flower"]],
  ["cloud", "nature", ["clouds"], ["smoke", "snowflake"]],
  ["flower", "nature", ["blossom"], ["tree", "cactus"]],
  ["igloo", "places", ["snowhouse"], ["tent", "snowman"]],
  ["island", "places", ["isle"], ["mountain", "beach"]],
  ["lighthouse", "places", ["light house"], ["house", "tower"]],
  ["mountain", "nature", ["mountains"], ["volcano", "hill"]],
  ["mushroom", "nature", ["toadstool"], ["umbrella", "flower"]],
  ["rainbow", "nature", ["rainbows"], ["bridge", "cloud"]],
  ["snowflake", "nature", ["snowflakes"], ["star", "flower"]],
  ["snowman", "characters", ["snow figure"], ["snowflake", "person"]],
  ["star", "space", ["stars"], ["sun", "snowflake"]],
  ["sun", "space", ["sunshine"], ["moon", "star"]],
  ["tornado", "nature", ["twister"], ["cloud", "volcano"]],
  ["tree", "nature", ["trees"], ["flower", "cactus"]],
  ["volcano", "nature", ["volcanoes"], ["mountain", "tornado"]],
  ["waterfall", "nature", ["waterfalls"], ["river", "fountain"]],
  ["castle", "places", ["fortress"], ["house", "lighthouse"]],
  ["bridge", "places", ["bridges"], ["tunnel", "road"]],
  ["house", "places", ["home"], ["castle", "barn"]],
  ["windmill", "places", ["wind mill"], ["fan", "lighthouse"]],
  ["barn", "places", ["barns"], ["house", "castle"]],

  ["airplane", "vehicles", ["aeroplane"], ["helicopter", "rocket"]],
  ["ambulance", "vehicles", ["ambulances"], ["firetruck", "car"]],
  ["boat", "vehicles", ["vessel"], ["submarine", "canoe"]],
  ["bus", "vehicles", ["buses"], ["van", "train"]],
  ["canoe", "vehicles", ["canoes"], ["boat", "kayak"]],
  ["car", "vehicles", ["automobile"], ["truck", "bus"]],
  ["helicopter", "vehicles", ["chopper"], ["airplane", "drone"]],
  ["motorcycle", "vehicles", ["motorbike"], ["bicycle", "scooter"]],
  ["rocket", "vehicles", ["rockets"], ["airplane", "missile"]],
  ["submarine", "vehicles", ["submersible"], ["boat", "whale"]],
  ["tractor", "vehicles", ["tractors"], ["truck", "bulldozer"]],
  ["train", "vehicles", ["locomotive"], ["bus", "tram"]],
  ["truck", "vehicles", ["lorry"], ["car", "tractor"]],

  ["alien", "characters", ["extraterrestrial"], ["astronaut", "robot"]],
  ["astronaut", "characters", ["spaceman"], ["alien", "knight"]],
  ["dragon", "characters", ["dragons"], ["dinosaur", "alligator"]],
  ["fairy", "characters", ["sprite"], ["angel", "butterfly"]],
  ["ghost", "characters", ["spirit"], ["mummy", "cloud"]],
  ["knight", "characters", ["armored knight"], ["pirate", "astronaut"]],
  ["mermaid", "characters", ["mermaids"], ["fairy", "dolphin"]],
  ["mummy", "characters", ["mummies"], ["ghost", "zombie"]],
  ["pirate", "characters", ["buccaneer"], ["knight", "sailor"]],
  ["robot", "characters", ["automaton"], ["astronaut", "alien"]],
  ["vampire", "characters", ["vampires"], ["ghost", "wizard"]],
  ["wizard", "characters", ["sorcerer"], ["knight", "vampire"]],
] as const satisfies readonly PromptSeed[];

const SINGLE_WORD_PRACTICE_EXCLUSIONS = new Set<string>([
  "ant", "bat", "beetle", "donkey", "hamster", "hedgehog", "jellyfish",
  "ladybug", "lobster", "raccoon", "rhinoceros", "scorpion", "snail", "swan",
  "anchor", "binoculars", "comb", "compass", "envelope", "fan", "paintbrush",
  "whistle", "cheese", "cherry", "grapes", "pretzel", "snowflake", "windmill",
  "ambulance", "canoe", "alien", "fairy", "knight", "mummy", "vampire",
]);

export const PROMPT_DECK: readonly PromptCard[] = SINGLE_WORD_PROMPT_SEEDS.map(
  ([prompt, category, aliases, rejectedAnswers]) => ({
    prompt,
    category,
    aliases,
    rejectedAnswers,
    practiceEligible: !SINGLE_WORD_PRACTICE_EXCLUSIONS.has(prompt),
  }),
);

export const PRACTICE_PROMPTS: readonly PromptCard[] = PROMPT_DECK.filter(
  (prompt) => prompt.practiceEligible,
);

export function randomPrompt(
  usedPrompts: Iterable<string> | string = [],
  practice = false,
): PromptCard {
  const deck = practice ? PRACTICE_PROMPTS : PROMPT_DECK;
  const used = new Set(typeof usedPrompts === "string" ? [usedPrompts] : usedPrompts);
  const available = deck.filter((card) => !used.has(card.prompt));
  const candidates = available.length > 0 ? available : deck;
  const random = crypto.getRandomValues(new Uint32Array(1))[0] ?? 0;
  const index = random % candidates.length;
  return candidates[index] ?? deck[0] ?? PROMPT_DECK[0]!;
}
