export interface PromptCard {
  readonly prompt: string;
  readonly category: string;
  readonly aliases: readonly string[];
  /** Known tempting guesses that intentionally omit or change a required concept. */
  readonly rejectedAnswers: readonly string[];
  readonly practiceEligible: boolean;
}

function card(
  prompt: string,
  category: string,
  aliases: readonly string[],
  rejectedAnswers: readonly string[],
  practiceEligible = true,
): PromptCard {
  return { prompt, category, aliases, rejectedAnswers, practiceEligible };
}

// Original cards intentionally favor silhouettes that read well under constrained geometry.
const BASE_PROMPT_DECK = [
  { prompt: "campfire", category: "outdoors", aliases: ["fire", "bonfire"] },
  {
    prompt: "robot gardener",
    category: "characters",
    aliases: ["gardening robot", "robot gardening"],
  },
  { prompt: "hot air balloon", category: "travel", aliases: ["air balloon"] },
  { prompt: "sleepy volcano", category: "nature", aliases: ["sleeping volcano"] },
  { prompt: "pancake tower", category: "food", aliases: ["stack of pancakes", "towering pancake stack"] },
  { prompt: "moon mailbox", category: "space", aliases: ["mailbox on the moon", "lunar mailbox"] },
  { prompt: "roller-skating octopus", category: "animals", aliases: ["octopus skating", "skating octopus"] },
  { prompt: "lighthouse", category: "places", aliases: ["light house"] },
  { prompt: "umbrella parade", category: "activities", aliases: ["parade of umbrellas"] },
  { prompt: "telescope", category: "objects", aliases: ["spyglass"] },
  { prompt: "submarine sandwich", category: "wordplay", aliases: ["sub sandwich", "sandwich submarine"] },
  { prompt: "mountain goat", category: "animals", aliases: ["goat on a mountain", "cliff climbing goat"] },
  { prompt: "birthday meteor", category: "space", aliases: ["meteor birthday", "birthday asteroid"] },
  { prompt: "detective duck", category: "characters", aliases: ["duck detective"] },
  { prompt: "treehouse", category: "places", aliases: ["tree house"] },
  { prompt: "kite festival", category: "outdoors", aliases: ["festival of kites", "sky full of kites"] },
  { prompt: "coffee rocket", category: "wordplay", aliases: ["rocket coffee", "coffee powered rocket"] },
  { prompt: "snail race", category: "activities", aliases: ["racing snails", "snails racing"] },
  { prompt: "desert island", category: "places", aliases: ["tropical desert island", "sandy deserted island"] },
  { prompt: "drum set", category: "music", aliases: ["drum kit", "full percussion set"] },
  { prompt: "penguin picnic", category: "animals", aliases: ["picnic with penguins", "picnic penguin"] },
  { prompt: "bicycle", category: "travel", aliases: ["bike"] },
  { prompt: "cloud factory", category: "fantasy", aliases: ["factory making clouds"] },
  { prompt: "cactus orchestra", category: "music", aliases: ["cactus band", "musical cactus"] },
  { prompt: "treasure map", category: "objects", aliases: ["map to treasure"] },
  { prompt: "flying library", category: "fantasy", aliases: ["library in the sky", "airborne library"] },
  { prompt: "snowman vacation", category: "activities", aliases: ["vacationing snowman", "snowman on vacation"] },
  { prompt: "pizza planet", category: "space", aliases: ["planet pizza", "pizza world"] },
  { prompt: "bridge", category: "places", aliases: ["river bridge"] },
  { prompt: "camera", category: "objects", aliases: ["photo camera"] },
  { prompt: "dancing teapot", category: "characters", aliases: ["teapot dancing"] },
  { prompt: "rainbow tunnel", category: "fantasy", aliases: ["tunnel rainbow"] },
  { prompt: "beach castle", category: "outdoors", aliases: ["sand castle", "sandcastle"] },
  { prompt: "astronaut fishing", category: "space", aliases: ["fishing astronaut", "astronaut fishing in space"] },
  { prompt: "dragon hatching from an egg", category: "fantasy", aliases: ["hatching dragon", "baby dragon hatching", "dragon coming out of an egg"] },
  { prompt: "train station", category: "travel", aliases: ["railway station"] },
  {
    prompt: "robot watering a plant",
    category: "characters",
    aliases: [
      "watering plant robot",
      "plant watering robot",
    ],
  },
  { prompt: "raccoon stealing a sandwich", category: "animals", aliases: ["raccoon with stolen sandwich", "sandwich thief raccoon"] },
  { prompt: "astronaut walking a dog", category: "space", aliases: ["astronaut dog walk", "space dog walk"] },
  {
    prompt: "cactus wearing a hat",
    category: "characters",
    aliases: [
      "cowboy cactus",
      "cactus in cowboy hat",
      "cactus wearing a cowboy hat",
      "cactus with a cowboy hat",
      "cactus with a hat",
    ],
  },
  {
    prompt: "octopus playing drums",
    category: "music",
    aliases: [
      "drumming octopus",
      "octopus drummer",
      "drum playing octopus",
      "octopus with drums",
    ],
  },
  { prompt: "toaster at the beach", category: "wordplay", aliases: ["beach toaster", "toaster on beach"] },
  { prompt: "moon fishing for a star", category: "space", aliases: ["moon catching a star", "fishing moon with star"] },
  { prompt: "bicycle with square wheels", category: "travel", aliases: ["square wheel bicycle", "square wheeled bike", "bike with square wheels"] },
  { prompt: "penguin delivering pizza", category: "characters", aliases: ["pizza delivery penguin", "penguin pizza courier"] },
  { prompt: "cloud using an umbrella", category: "wordplay", aliases: ["cloud with umbrella", "umbrella cloud"] },
] as const;

type BasePromptName = (typeof BASE_PROMPT_DECK)[number]["prompt"];

const BASE_REJECTIONS: Record<BasePromptName, readonly string[]> = {
  campfire: ["fireplace", "candle"],
  "robot gardener": ["robot", "human gardener"],
  "hot air balloon": ["balloon", "blimp"],
  "sleepy volcano": ["volcano", "erupting volcano"],
  "pancake tower": ["pancakes", "pancake"],
  "moon mailbox": ["mailbox", "moon"],
  "roller-skating octopus": ["octopus", "roller skates"],
  lighthouse: ["house", "watchtower"],
  "umbrella parade": ["umbrella", "parade"],
  telescope: ["microscope", "binoculars"],
  "submarine sandwich": ["submarine", "sandwich"],
  "mountain goat": ["goat", "sheep"],
  "birthday meteor": ["meteor", "birthday cake"],
  "detective duck": ["duck", "detective"],
  treehouse: ["house", "tree"],
  "kite festival": ["kite", "kites"],
  "coffee rocket": ["rocket", "coffee"],
  "snail race": ["snail", "running race"],
  "desert island": ["island", "tropical island"],
  "drum set": ["drum", "cymbal"],
  "penguin picnic": ["penguin", "picnic"],
  bicycle: ["motorcycle", "unicycle"],
  "cloud factory": ["factory", "cloud"],
  "cactus orchestra": ["cactus", "orchestra"],
  "treasure map": ["map", "treasure"],
  "flying library": ["library", "flying book"],
  "snowman vacation": ["snowman", "beach vacation"],
  "pizza planet": ["pizza", "planet"],
  bridge: ["road", "tunnel"],
  camera: ["photograph", "projector"],
  "dancing teapot": ["teapot", "tea party"],
  "rainbow tunnel": ["tunnel", "rainbow"],
  "beach castle": ["castle", "beach"],
  "astronaut fishing": ["astronaut", "fishing"],
  "dragon hatching from an egg": ["dragon", "egg"],
  "train station": ["train", "bus station"],
  "robot watering a plant": ["robot", "plant", "robot gardener"],
  "raccoon stealing a sandwich": ["raccoon", "raccoon eating a sandwich"],
  "astronaut walking a dog": ["astronaut", "dog"],
  "cactus wearing a hat": ["cactus", "hat"],
  "octopus playing drums": ["octopus", "drums"],
  "toaster at the beach": ["toaster", "beach"],
  "moon fishing for a star": ["moon", "star"],
  "bicycle with square wheels": ["bicycle", "round wheel bicycle"],
  "penguin delivering pizza": ["penguin", "pizza"],
  "cloud using an umbrella": ["cloud", "umbrella"],
};

const EXPANDED_PROMPTS: readonly PromptCard[] = [
  card("sleepy turtle", "animals", ["sleeping turtle", "tired turtle", "drowsy turtle"], ["turtle", "slow turtle"]),
  card("cat in a cardboard box", "animals", ["boxed cat", "cat inside a box"], ["cat", "cardboard box"]),
  card("dog chasing its tail", "animals", ["tail chasing dog", "dog spinning after its tail"], ["dog", "spinning dog"]),
  card("bear reading a book", "animals", ["reading bear", "bookish bear reading"], ["bear", "book"]),
  card("fox riding a scooter", "animals", ["scooter riding fox", "fox on a scooter"], ["fox", "scooter"]),
  card("owl wearing glasses", "animals", ["bespectacled owl", "owl with spectacles"], ["owl", "glasses"]),
  card("rabbit pulling a wagon", "animals", ["wagon pulling rabbit", "bunny pulling a wagon"], ["rabbit", "wagon"]),
  card("giraffe under a raincloud", "animals", ["rainy giraffe", "giraffe beneath a rain cloud"], ["giraffe", "raincloud"]),
  card("lion brushing its mane", "animals", ["grooming lion", "lion combing its mane"], ["lion", "lion with a mane"]),
  card("elephant flying a kite", "animals", ["kite flying elephant", "elephant with a flying kite"], ["elephant", "kite"]),
  card("mouse lifting a barbell", "animals", ["weightlifting mouse", "strong mouse with barbell"], ["mouse", "barbell"]),
  card("whale carrying a sailboat", "animals", ["whale with a sailboat", "sailboat riding a whale"], ["whale", "sailboat"]),
  card("seal balancing a ball", "animals", ["ball balancing seal", "circus seal with a ball"], ["seal", "beach ball"]),
  card("frog on a lily pad", "animals", ["lily pad frog", "frog sitting on a lily pad"], ["frog", "lily pad"]),
  card("crab building a sandcastle", "animals", ["sandcastle building crab", "crab making a sand castle"], ["crab", "sandcastle"]),
  card("koala holding balloons", "animals", ["balloon holding koala", "koala with balloons"], ["koala", "balloons"]),
  card("zebra painting stripes", "animals", ["stripe painting zebra", "zebra painting its own stripes"], ["zebra", "striped zebra"]),
  card("pig wearing rain boots", "animals", ["pig in rain boots", "boot wearing pig"], ["pig", "boots"]),
  card("chicken playing chess", "animals", ["chess playing chicken", "chicken at a chessboard"], ["chicken", "chess"]),
  card("cow jumping over the moon", "animals", ["moon jumping cow", "cow leaping over the moon"], ["cow", "moon"]),
  card("shark at a tea party", "animals", ["tea party shark", "shark drinking tea at a party"], ["shark", "tea"]),
  card("squirrel burying an acorn", "animals", ["acorn burying squirrel", "squirrel hiding a nut"], ["squirrel", "acorn"]),
  card("hedgehog carrying apples", "animals", ["apple carrying hedgehog", "hedgehog with apples"], ["hedgehog", "apple"]),
  card("camel carrying a surfboard", "animals", ["surfboard carrying camel", "camel holding a surfboard"], ["camel", "surfboard"]),
  card("panda flying a paper airplane", "animals", ["paper plane flying panda", "panda throwing a paper airplane"], ["panda", "paper airplane"]),
  card("flamingo on a skateboard", "animals", ["skateboarding flamingo", "flamingo riding a skateboard"], ["flamingo", "skateboard"]),
  card("monkey taking a selfie", "animals", ["selfie taking monkey", "monkey posing for a selfie"], ["monkey", "selfie"]),
  card("beaver fixing a dam", "animals", ["dam repairing beaver", "beaver repairing a dam"], ["beaver", "dam"]),
  card("sheep knitting a scarf", "animals", ["scarf knitting sheep", "knitting sheep with scarf"], ["sheep", "scarf"]),
  card("turtle with a jetpack", "animals", ["jetpack turtle", "flying turtle with jetpack"], ["turtle", "flying turtle"]),
  card("bee carrying a suitcase", "animals", ["suitcase carrying bee", "traveling bee with luggage"], ["bee", "suitcase"]),
  card("horse in roller skates", "animals", ["roller skating horse", "horse wearing skates"], ["horse", "skates"]),
  card("duck sailing a leaf boat", "animals", ["leaf boat duck", "duck in a leaf boat"], ["duck", "boat"]),
  card("cat conducting an orchestra", "animals", ["orchestra conductor cat", "musical conductor cat"], ["cat", "orchestra"]),
  card("dog baking cookies", "animals", ["cookie baking dog", "baker dog with cookies"], ["dog", "cookies"]),
  card("bear camping in a tent", "animals", ["camping bear", "bear inside a tent"], ["bear", "tent"]),
  card("fox roasting marshmallows", "animals", ["marshmallow roasting fox", "fox roasting treats by a fire"], ["fox", "campfire"]),
  card("owl delivering mail", "animals", ["mail carrier owl", "postal delivery owl"], ["owl", "mailbox"]),
  card("rabbit painting eggs", "animals", ["egg painting rabbit", "bunny decorating eggs"], ["rabbit", "eggs"]),
  card("giraffe wearing a bow tie", "animals", ["bow tie giraffe", "giraffe with a bow tie"], ["giraffe", "necktie giraffe"]),
  card("lion blowing bubbles", "animals", ["bubble blowing lion", "lion making soap bubbles"], ["lion", "bubbles"]),
  card("elephant on a trampoline", "animals", ["trampoline jumping elephant", "bouncing elephant on a trampoline"], ["elephant", "trampoline"]),
  card("mouse rowing a walnut boat", "animals", ["walnut boat mouse", "mouse in a nut boat"], ["mouse", "boat"]),
  card("whale under a starry sky", "animals", ["stargazing whale", "whale beneath the stars"], ["whale", "night sky"]),
  card("seal playing a trumpet", "music", ["trumpet playing seal", "seal musician with trumpet"], ["seal", "trumpet"]),
  card("frog catching fireflies", "animals", ["firefly catching frog", "frog chasing fireflies"], ["frog", "fireflies"]),
  card("crab wearing oven mitts", "animals", ["oven mitt crab", "crab with cooking mitts"], ["crab", "mittens"]),
  card("koala sleeping in a hammock", "animals", ["hammock sleeping koala", "koala napping in a hammock"], ["koala", "hammock"]),
  card("zebra crossing a tightrope", "animals", ["tightrope walking zebra", "acrobat zebra on a rope"], ["zebra", "tightrope"]),
  card("pig flying a helicopter", "animals", ["helicopter pilot pig", "pig in a helicopter"], ["pig", "helicopter"]),
  card("chicken watering flowers", "animals", ["flower watering chicken", "gardening chicken with flowers"], ["chicken", "flowers"]),
  card("cow playing the violin", "music", ["violin playing cow", "cow musician with violin"], ["cow", "violin"]),
  card("shark wearing a life jacket", "animals", ["life jacket shark", "shark in a flotation vest"], ["shark", "jacket"]),
  card("squirrel riding a unicycle", "animals", ["unicycle riding squirrel", "one wheel riding squirrel"], ["squirrel", "bicycle"]),
  card("hedgehog under a mushroom", "animals", ["mushroom shelter hedgehog", "hedgehog beneath a mushroom"], ["hedgehog", "mushroom"]),
  card("camel carrying a snowman", "animals", ["camel with a snowman", "snowman riding a camel"], ["camel", "snowman"]),
  card("panda making pancakes", "animals", ["pancake cooking panda", "panda chef with pancakes"], ["panda", "pancakes"]),
  card("flamingo playing hopscotch", "animals", ["hopscotch flamingo", "flamingo hopping through squares"], ["flamingo", "hopscotch"]),
  card("monkey juggling bananas", "animals", ["banana juggling monkey", "monkey juggler with bananas"], ["monkey", "bananas"]),
  card("beaver in a canoe", "animals", ["canoeing beaver", "beaver paddling a canoe"], ["beaver", "canoe"]),
  card("sheep wearing headphones", "animals", ["headphone wearing sheep", "sheep listening to music"], ["sheep", "headphones"]),
  card("goat on a rooftop", "animals", ["rooftop goat", "goat standing on a roof"], ["goat", "mountain goat"]),
  card("penguin building an igloo", "animals", ["igloo building penguin", "penguin making an igloo"], ["penguin", "igloo"]),
  card("octopus holding balloons", "animals", ["balloon holding octopus", "octopus carrying balloons", "octopus with balloons"], ["octopus", "balloons"]),
  card("snail carrying a birthday cake", "animals", ["cake carrying snail", "birthday snail with cake"], ["snail", "cake"]),
  card("raccoon washing socks", "animals", ["sock washing raccoon", "laundry raccoon washing socks"], ["raccoon", "socks"]),
  card("astronaut planting a flag", "space", ["flag planting astronaut", "astronaut raising a flag"], ["astronaut", "flag"]),
  card("robot walking a goldfish", "characters", ["goldfish walking robot", "robot with a fish bowl leash"], ["robot", "goldfish"]),
  card("pirate using a laptop", "characters", ["laptop pirate", "pirate working on a computer"], ["pirate", "laptop"]),
  card("wizard brushing teeth", "characters", ["tooth brushing wizard", "wizard with a toothbrush"], ["wizard", "toothbrush"]),
  card("knight riding a bicycle", "characters", ["bicycle riding knight", "knight on a bike"], ["knight", "bicycle"]),
  card("mermaid reading a newspaper", "characters", ["newspaper reading mermaid", "mermaid reading the news"], ["mermaid", "newspaper"]),
  card("ghost carrying groceries", "characters", ["grocery carrying ghost", "ghost with shopping bags"], ["ghost", "shopping bags"]),
  card("alien grilling burgers", "characters", ["burger grilling alien", "alien at a burger barbecue"], ["alien", "burger"]),
  card("vampire applying sunscreen", "characters", ["sunscreen applying vampire", "vampire using sunblock"], ["vampire", "sunscreen"]),
  card("mummy at a birthday party", "characters", ["birthday party mummy", "mummy celebrating a birthday"], ["mummy", "birthday cake"]),
  card("witch vacuuming a cloud", "characters", ["cloud vacuuming witch", "witch with a vacuum cleaner and cloud"], ["witch", "cloud"]),
  card("fairy repairing a bicycle", "characters", ["bicycle repair fairy", "fairy fixing a bike"], ["fairy", "bicycle"]),
  card("giant holding a tiny umbrella", "characters", ["umbrella holding giant", "giant with a small umbrella"], ["giant", "umbrella"]),
  card("superhero doing laundry", "characters", ["laundry washing superhero", "superhero washing clothes"], ["superhero", "washing machine"]),
  card("astronaut making toast", "space", ["toast making astronaut", "astronaut using a toaster"], ["astronaut", "toaster"]),
  card("robot fishing in a bathtub", "characters", ["bathtub fishing robot", "robot with fishing rod in a bath"], ["robot", "bathtub"]),
  card("pirate watering a cactus", "characters", ["cactus watering pirate", "pirate with a watering can and cactus"], ["pirate", "cactus"]),
  card("wizard riding a vacuum", "characters", ["vacuum riding wizard", "wizard on a vacuum cleaner"], ["wizard", "broomstick"]),
  card("knight roasting a marshmallow", "characters", ["marshmallow roasting knight", "knight roasting a treat by a fire"], ["knight", "campfire"]),
  card("mermaid walking a poodle", "characters", ["poodle walking mermaid", "mermaid taking a poodle for a walk"], ["mermaid", "poodle"]),
  card("ghost stuck in traffic", "characters", ["traffic jam ghost", "ghost driving in traffic"], ["ghost", "car"]),
  card("alien walking dogs", "characters", ["dog walking alien", "alien with dogs on leashes"], ["alien", "dogs"]),
  card("vampire baking garlic bread", "characters", ["garlic bread baking vampire", "vampire cooking garlic bread"], ["vampire", "garlic"]),
  card("mummy playing tennis", "characters", ["tennis playing mummy", "mummy with a tennis racket"], ["mummy", "tennis"]),
  card("witch making popcorn", "characters", ["popcorn making witch", "witch with a popcorn pot"], ["witch", "popcorn"]),
  card("fairy painting a rainbow", "characters", ["rainbow painting fairy", "fairy with a rainbow paintbrush"], ["fairy", "rainbow"]),
  card("giant tying shoelaces", "characters", ["shoelace tying giant", "giant tying a shoe"], ["giant", "shoe"]),
  card("superhero stuck in an elevator", "characters", ["elevator trapped superhero", "superhero inside a broken lift"], ["superhero", "elevator"]),
  card("smiling sun behind a cloud", "nature", ["sun peeking through clouds", "happy sun behind a cloud"], ["sun", "cloud"]),
  card("moon wearing headphones", "space", ["headphone wearing moon", "moon listening to music"], ["moon", "headphones"]),
  card("cloud raining hearts", "fantasy", ["heart raining cloud", "cloud with heart shaped rain"], ["cloud", "raincloud"]),
  card("tornado carrying a barn", "nature", ["barn lifting tornado", "tornado with a flying barn"], ["tornado", "barn"]),
  card("volcano wearing earmuffs", "nature", ["earmuff wearing volcano", "volcano with ear warmers"], ["volcano", "earmuffs"]),
  card("waterfall flowing into a teacup", "fantasy", ["teacup waterfall", "waterfall pouring into a tea cup"], ["waterfall", "teacup"]),
  card("iceberg with a doorway", "nature", ["doorway iceberg", "iceberg entrance"], ["iceberg", "igloo"]),
  card("rainbow over a toolbox", "fantasy", ["toolbox beneath a rainbow", "toolbox under a rainbow"], ["rainbow", "toolbox"]),
  card("thundercloud playing drums", "music", ["drumming thundercloud", "storm cloud with drums"], ["thundercloud", "drums"]),
  card("mountain wearing a scarf", "nature", ["scarf wearing mountain", "mountain wrapped in a scarf"], ["mountain", "scarf"]),
];

const PRACTICE_EXCLUSIONS = new Set<string>([
  "submarine sandwich",
  "birthday meteor",
  "umbrella parade",
  "coffee rocket",
  "cloud factory",
  "cactus orchestra",
  "flying library",
  "snowman vacation",
  "pizza planet",
  "rainbow tunnel",
  "astronaut fishing",
  "dragon hatching from an egg",
  "robot watering a plant",
  "raccoon stealing a sandwich",
  "astronaut walking a dog",
  "cactus wearing a hat",
  "octopus playing drums",
  "toaster at the beach",
  "moon fishing for a star",
  "bicycle with square wheels",
  "penguin delivering pizza",
  "cloud using an umbrella",
  "whale carrying a sailboat",
  "cow jumping over the moon",
  "shark at a tea party",
  "zebra painting stripes",
  "cat conducting an orchestra",
  "whale under a starry sky",
  "pig flying a helicopter",
  "camel carrying a snowman",
  "octopus holding balloons",
  "robot walking a goldfish",
  "witch vacuuming a cloud",
  "giant holding a tiny umbrella",
  "superhero doing laundry",
  "robot fishing in a bathtub",
  "wizard riding a vacuum",
  "mermaid walking a poodle",
  "ghost stuck in traffic",
  "alien walking dogs",
  "vampire baking garlic bread",
  "superhero stuck in an elevator",
  "waterfall flowing into a teacup",
  "iceberg with a doorway",
  "rainbow over a toolbox",
  "thundercloud playing drums",
  "tornado carrying a barn",
  "cloud raining hearts",
  "mouse rowing a walnut boat",
  "bee carrying a suitcase",
]);

export const PROMPT_DECK: readonly PromptCard[] = [
  ...BASE_PROMPT_DECK.map((base) => ({
    ...base,
    rejectedAnswers: BASE_REJECTIONS[base.prompt],
    practiceEligible: !PRACTICE_EXCLUSIONS.has(base.prompt),
  })),
  ...EXPANDED_PROMPTS.map((prompt) => ({
    ...prompt,
    practiceEligible: !PRACTICE_EXCLUSIONS.has(prompt.prompt),
  })),
];

export const PRACTICE_PROMPTS: readonly PromptCard[] = PROMPT_DECK.filter(
  (prompt) => prompt.practiceEligible,
);

export function randomPrompt(
  usedPrompts: Iterable<string> | string = [],
  practice = false,
): PromptCard {
  const deck = practice ? PRACTICE_PROMPTS : PROMPT_DECK;
  const used = new Set(typeof usedPrompts === "string" ? [usedPrompts] : usedPrompts);
  const available = deck.filter((card) => !used.has(card.prompt));
  const candidates = available.length > 0 ? available : deck;
  const random = crypto.getRandomValues(new Uint32Array(1))[0] ?? 0;
  const index = random % candidates.length;
  return candidates[index] ?? deck[0] ?? PROMPT_DECK[0]!;
}
